Homework 04 - Add bastion host to GCP
Otus-DevOps-2018-02/romankarpushkin_infra pull request #3
Opened 2018-03-16 10:07 UTC by romankarpushkin

# Выполнено ДЗ № 4

 - [x] Основное ДЗ
 - [x] Задание со * (решение описано в README.MD)

## В процессе сделано:
 - Созданы инстансы bastion и someinternal host
bastion_IP = 35.204.130.174
someinternalhost_IP = 10.164.0.3
 - Создан ключ и настроено подключение по ssh к обоим хостам в одну строку (с использованием ~/.ssh/config)

## Как проверить работоспособность:
 - Перейти по ссылке https://35.204.130.174
 - Подключиться к серверу используя cloud-bastion.ovpn используя логин и пинкод из задания

## PR checklisk
 - [x] Выставил label с номером домашнего задания gcp
 - [x] Выставил label с темой домашнего задания homework-4

2018-03-22 08:20 UTC, vitkhab requested changes
Делаю `Request changes` с целью обратить твое внимание на то, что у тебя ветка называется `cloud_bastion`, хотя в ДЗ мы просили назвать ее `cloud-bastion` (с дефисом вместо подчеркивания).  Из-за этого не запустились нужные тесты и успешная проверка TravisCI в данном случае не говорит ни о чем. Прошу в следующий раз быть внимательнее.

В остальном, все выглядит хорошо. Классно, что ты нашел решение для дополнительного задания.
Описание и Readme оформлены хорошо.

Удали, пожалуйста, лишние строчки из `setupvpn.sh`, как подтверждение, что ты увидел сообщение. Этого будет достаточно для приемки работы.

2018-03-22 08:20 UTC, vitkhab commented on setupvpn.sh
> +cat <<EOF> setupvpn.sh
Это строчка лишняя

2018-03-22 08:20 UTC, vitkhab commented on setupvpn.sh
> +EOF
И эта тоже

2018-03-24 14:33 UTC, romankarpushkin commented
@vitkhab Спасибо, удалил ненужные строки из setupvpn.sh

2018-04-06 10:20 UTC, Nklya approved these changes
Да, теперь ок 👍

2018-04-06 10:29 UTC, vitkhab approved these changes

2018-04-08 09:42 UTC, merged